#%RAML 0.8
title: ABC-C
version: 1.0
/ordercoffe:
 post:
   responses: 
     201:
       body: 
         application/json:
           example: |
             { 
             "machineno":" 0012324", 
             "milk":" 75", 
             "water":"200", 
             "coffepowder":"30",
             "choclate":"20"
             "cups":300
             }